spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    type: org.mariadb.jdbc.MariaDbDataSource
    #    schema: classpath:form-schema.sql
    #    data: classpath:form-data.sql
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 50
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 3000
      read-only: false
      login-timeout: 5


#虽然两种都可以运行成功，但下面这种写法才是2.4版本的最好的写法，原因是2.4版本中官方将配置文件的加载进行了更新，
#所以如果使用的是2.4版本推荐用下面的这种写法，至于原因就是为了提升对 Kubernetes 的原生支持而作的修改
#spring:
#  profiles: pro

---
#开发环境
spring:
  #  profiles: dev
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://192.168.111.103:13306/wes_all?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: shdy123!
    name: wes_all

---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
  datasource:
    url: jdbc:mariadb://192.168.111.103:13306/wes_all?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: shdy123!
    name: wes_all
---
#本地环境
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    url: jdbc:mysql://101.35.194.46:3306/nezhadb?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: admin
    password: 7fFsECXmpjX5y3Xw

---
#生产环境
spring:
  config:
    activate:
      on-profile: prd
  datasource:
    url: jdbc:mariadb://dev-mariadb/wes?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: ENC(QNYjbKWdPW89+oxYzxHVGA==)
#    hikari:
#      connection-timeout: 60000
#      minimum-idle: 5
#      maximum-pool-size: 10
#      idle-timeout: 300000
#      max-lifetime: 1200000
#      auto-commit: true
#      connection-test-query: SELECT 1
#      validation-timeout: 3000
#      read-only: false
#      login-timeout: 5
#      jdbc-url: jdbc:mysql://sh-cdb-1qjrazc8.sql.tencentcdb.com:63915/wes?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#      username: admin
#      password: ENC(mY6NIyj0expFSKj0ahyGhwK189kA5fcB)



